services:
  pchirp:
    image: chirper
    container_name: chirper
    restart: unless-stopped
    networks:
      - chirper #if you're using networks between containers
    depends_on:
      - mysql
      #Nginx server
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    # volumes:
    #   - ~/mysql:/var/lib/mysql
      # - './docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    networks:
      - chirper
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s
networks:
  chirper:
    driver: bridge
# volumes:
#   chirp-mysql:
#     driver: local
